baseline:
  compare: false
  name: HRRR
  template: https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.{yyyymmdd}/conus/hrrr.t{hh}z.wrfprsf{ff}.grib2
cycles:
  start: "2024-04-01T02:00:00"
  step: "01:00:00"
  stop: "2024-04-07T23:00:00"
forecast:
  mask:
    - [52.61564933, 225.90452027]
    - [52.61564933, 255.00000000]
    - [21.138123,   255.00000000]
    - [21.138123,   225.90452027]
  name: ResHRRR
  path: /path/to/forecast.zarr
  projection:
    proj: latlon
leadtimes:
  start: "01:00:00"
  step: "01:00:00"
  stop: "01:00:00"
meta:
  grids: "{{ meta.workdir }}/grids"
  levels: &levels [200, 300, 475, 800, 825, 850, 875, 900, 925, 950, 975, 1000]
  workdir: /path/to/workdir
paths:
  grids:
    baseline: "{{ meta.grids }}/baseline"
    forecast: "{{ meta.grids }}/forecast"
  run: "{{ meta.workdir }}/run"
variables:
  HGT:
    level_type: isobaricInhPa
    levels: *levels
    name: gh
  REFC:
    level_type: atmosphere
    name: refc
  SPFH:
    level_type: isobaricInhPa
    levels: *levels
    name: q
  T2M:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  TMP:
    level_type: isobaricInhPa
    levels: *levels
    name: t
  UGRD:
    level_type: isobaricInhPa
    levels: *levels
    name: u
  VGRD:
    level_type: isobaricInhPa
    levels: *levels
    name: v
  VVEL:
    level_type: isobaricInhPa
    levels: *levels
    name: w
